### ISSUE TITLE
token error

### ISSUE THREAD

**Issue by huiwudiyi** [zhpmatrix/BERTem#1]
I use  SemEval Task8 data.
Arguments: (['[CLS]', 'the', 'system', 'as', 'described', 'above', 'has', 'its', 'greatest', 'application', 'in', 'an', 'array', '##ed',     '\<s1\>', 'configuration', '\<e1\>', 'of', 'antenna', '\<s2\>', 'elements', '\<e2\>', '.', '[SEP]'],)
but there is no '\<s1\>' '\<e1\>' in  vocab!

**Comment by zhpmatrix** [comment]
add '\<s1\>', '\<e1\>', '\<s2\>', '\<e2\>' into the vocab.txt. @huiwudiyi

**Comment by huiwudiyi** [comment]
Thanks，I have solved it!
